/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interface;
import Api.Api;
import Structures.LinkedList2;
import Main.Main;
import Structures.GestionEdges;
import Structures.GestionSites;
import Structures.Graph;
import Structures.ListNode;
import Structures.Site;
import Table.ModeladorTablas;
import com.google.maps.errors.ApiException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import Structures.ClientTour;

/**
 *
 * @author marip
 */
public class Empresa extends javax.swing.JFrame {
    
    private int contador = 0;
        
    public GestionEdges gestion_edges; // DEBE ESTAR DECLARADO E INICIALIZADO 

    public GestionEdges getGestion_edges() {
        return gestion_edges;
    }

    public void setGestion_edges(GestionEdges gestion_edges) {
        this.gestion_edges = gestion_edges;
    }
    
        public GestionSites gestion_sitios; // DEBE ESTAR DECLARADO E INICIALIZADO 

    public GestionSites getGestion_sitios() {
        return gestion_sitios;
    }

    public void setGestion_sitios(GestionSites gestion_sitios) {
        this.gestion_sitios = gestion_sitios;
    }
    
    

    /**
     * GENERAR GETTER AND SETTER DE LA TABLA
     *
     * @return
     */
       public JTable getTabla_empresa() {
        return tabla_empresa;
    }

    public void setTabla_empresa(JTable tabla_empresa) {
        this.tabla_empresa = tabla_empresa;
    }
    
 /** Creates new form Empresa */
    public Empresa() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public void actualizarTabla() {

        ModeladorTablas.vaciarTabla(tabla_empresa);
        Object[] filaNueva;
        ListNode<Site> temp = gestion_sitios.getSites().getInicio();
        for (int i = 0; i < gestion_sitios.getSites().getSize(); i++) {
            filaNueva = new Object[]{temp.getElemento().getId(),
                temp.getElemento().getName(),
                temp.getElemento().getPrice(),
                temp.getElemento().getDescription(),
                temp.getElemento().getActivities(),
                temp.getElemento().getLat(),
                temp.getElemento().getLng(),
                temp.getElemento().getAddress()};
            ModeladorTablas.nuevaFila(tabla_empresa, filaNueva);
            temp = temp.getNodoSig();
        }
    }

     public void eliminarDesdeTabla() throws Exception {
        int rowNum = tabla_empresa.getSelectedRow();
        String elim = ModeladorTablas.obtenerValorCelda(tabla_empresa, rowNum, 0);//ModeladorTablas.obtenerValorCelda(tabla_animales, rowNum, 0);
        gestion_sitios.deleteSites(elim);
        actualizarTabla();
    }

   

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.n
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        txtDistancia = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDuracion = new javax.swing.JTextField();
        btnActualizar = new javax.swing.JButton();
        btnOrigen = new javax.swing.JButton();
        fieldaddress1 = new javax.swing.JTextField();
        fieldaddress2 = new javax.swing.JTextField();
        btnDestino = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        btnTour = new javax.swing.JButton();
        txtId1 = new javax.swing.JTextField();
        txtId2 = new javax.swing.JTextField();
        txtnombre2 = new javax.swing.JTextField();
        lblTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_empresa = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAgregar.setBackground(new java.awt.Color(255, 255, 255));
        btnAgregar.setForeground(new java.awt.Color(0, 153, 153));
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, -1, -1));

        btnMenu.setBackground(new java.awt.Color(255, 255, 255));
        btnMenu.setForeground(new java.awt.Color(0, 153, 153));
        btnMenu.setText("Menu");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });
        jPanel1.add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 380, -1, -1));
        jPanel1.add(txtDistancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 460, 110, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Distancia");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Duración");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 460, -1, -1));
        jPanel1.add(txtDuracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 460, 100, -1));

        btnActualizar.setBackground(new java.awt.Color(255, 255, 255));
        btnActualizar.setForeground(new java.awt.Color(0, 153, 153));
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jPanel1.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 380, -1, -1));

        btnOrigen.setForeground(new java.awt.Color(0, 153, 153));
        btnOrigen.setText("Elegir origen");
        btnOrigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrigenActionPerformed(evt);
            }
        });
        jPanel1.add(btnOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, -1, -1));
        jPanel1.add(fieldaddress1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 80, 110, -1));
        jPanel1.add(fieldaddress2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 120, 110, -1));

        btnDestino.setForeground(new java.awt.Color(0, 153, 153));
        btnDestino.setText("Elegir destino");
        btnDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDestinoActionPerformed(evt);
            }
        });
        jPanel1.add(btnDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, -1, -1));

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 170, 110, -1));

        btnTour.setForeground(new java.awt.Color(0, 153, 153));
        btnTour.setText("Ver Tour");
        btnTour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTourActionPerformed(evt);
            }
        });
        jPanel1.add(btnTour, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 460, -1, -1));
        jPanel1.add(txtId1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 220, 110, -1));
        jPanel1.add(txtId2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 270, 110, -1));

        txtnombre2.setText("jTextField1");
        jPanel1.add(txtnombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 310, -1, -1));

        lblTitulo.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("Crear Ruta Empresa");
        jPanel1.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, -1, -1));

        tabla_empresa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla_empresa);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 580, 280));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        Menu menu =  new Menu();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        this.actualizarTabla();
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrigenActionPerformed
        int indice = tabla_empresa.getSelectedRow();
        String data = (String)tabla_empresa.getValueAt(indice, 7);
        fieldaddress1.setText(data);
        String name = (String)tabla_empresa.getValueAt(indice, 1);
        txtNombre.setText(name);
        String id = (String)tabla_empresa.getValueAt(indice,0);
        txtId1.setText(id);
        
        
        
    }//GEN-LAST:event_btnOrigenActionPerformed

    private void btnDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDestinoActionPerformed
        int indice = tabla_empresa.getSelectedRow();
        String data = (String)tabla_empresa.getValueAt(indice, 7);
        fieldaddress2.setText(data);
        String id = (String)tabla_empresa.getValueAt(indice,0);
        txtId2.setText(id);
        String name = (String)tabla_empresa.getValueAt(indice, 1);
        txtnombre2.setText(name);
    }//GEN-LAST:event_btnDestinoActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        Api api = new Api();
        try {
            String a = String.valueOf(api.getDuration(fieldaddress1.getText(),fieldaddress2.getText()));
            txtDuracion.setText(a);
            String b = String.valueOf(api.getDriveDist(fieldaddress1.getText(),fieldaddress2.getText()));
            txtDistancia.setText(b);
        } catch (ApiException ex){
            Logger.getLogger(Empresa.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(Empresa.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Empresa.class.getName()).log(Level.SEVERE, null, ex);
        }
        String id = String.valueOf(contador);
        String nombre = txtNombre.getText();
       String duracion = txtDuracion.getText();
       String distancia = txtDistancia.getText();
        int origen = Integer.parseInt(txtId1.getText());
        int destino = Integer.parseInt(txtId1.getText());
        String address = fieldaddress1.getText();
       
        this.getGestion_edges().createEdges(id,nombre,duracion,distancia,address);
        
        Graph graph = new Graph();
        graph.addEdge(origen, destino,0);
     
        
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnTourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTourActionPerformed
        Tour clienttour = new Tour();
        clienttour.setVisible(true);
        this.setVisible(false);
        
         clienttour.setGestion_edges(Main.edges);// global lista
        
        
        Object[] columnasEdges = new Object[] {"Id","Nombre","Distancia","Duracion", "Direccion"};        
        clienttour.getTabla_tour().setModel(ModeladorTablas.generarModeloDeTabla(5, columnasEdges));
        clienttour.getTabla_tour().setAutoCreateRowSorter(true);
        clienttour.actualizarTabla();
    }//GEN-LAST:event_btnTourActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnDestino;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnOrigen;
    private javax.swing.JButton btnTour;
    private javax.swing.JTextField fieldaddress1;
    private javax.swing.JTextField fieldaddress2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tabla_empresa;
    private javax.swing.JTextField txtDistancia;
    private javax.swing.JTextField txtDuracion;
    private javax.swing.JTextField txtId1;
    private javax.swing.JTextField txtId2;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtnombre2;
    // End of variables declaration//GEN-END:variables

}
